import pytest
import os
import json
import asyncio
from backend.services.registration_service import RegistrationService
import shutil

@pytest.fixture(scope="module")
def setup_test_environment():
    """
    Mocks the file system state that the upload endpoint would normally create.
    """
    session_id = "test_e2e_session_999"
    img_dir = f"backend/cache/images/{session_id}"
    os.makedirs(img_dir, exist_ok=True)
    
    # Copy synthetic dataset into the cache
    shutil.copy("data/synthetic/pair_001/source.png", os.path.join(img_dir, "source.png"))
    shutil.copy("data/synthetic/pair_001/reference.png", os.path.join(img_dir, "reference.png"))
    
    yield session_id
    
    # Cleanup (Optional in CI, but good practice locally)
    # shutil.rmtree(img_dir, ignore_errors=True)
    # shutil.rmtree(f"backend/cache/results/{session_id}", ignore_errors=True)

@pytest.mark.asyncio
async def test_full_registration_pipeline(setup_test_environment):
    """
    Directly invokes the async RegistrationService bypassing the HTTP layer.
    Guarantees the mathematical core can ingest the cached binaries and 
    deterministically spit out a summary.json with an H_matrix.
    """
    session_id = setup_test_environment
    
    # Run the pipeline
    await RegistrationService.execute_pipeline(session_id)
    
    # Assert result payload generated
    result_path = f"backend/cache/results/{session_id}/summary.json"
    assert os.path.exists(result_path), "summary.json was not generated by the pipeline"
    
    with open(result_path, "r") as f:
        data = json.load(f)
        
    # Mathematical Assertions
    assert "rmse" in data
    assert data["rmse"] != "FAILED"
    assert "inliers" in data
    assert data["inliers"] > 0
    assert "H_matrix" in data
    assert len(data["H_matrix"]) == 3
    assert len(data["H_matrix"][0]) == 3
    
    # Check Explainability generated
    idx = data["dossier_index"]
    assert idx is not None
    assert os.path.exists(f"backend/cache/results/{session_id}/dossier_{idx}.json")
